DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(255) NOT NULL,
	AUTHOR_ID BIGINT,
	GENRE_ID BIGINT,
	foreign key (AUTHOR_ID) references AUTHOR(ID),
	foreign key (GENRE_ID) references GENRE(ID)
);